FROM debian:buster

RUN apt-get update -y && apt-get install -y wget php7.3-fpm php-mysql
RUN wget https://wordpress.org/latest.tar.gz
RUN tar xvf latest.tar.gz
COPY ph.conf /etc/php/7.3/fpm/pool.d/www.conf
RUN mkdir -p /var/www/html
RUN cp -r wordpress/* /var/www/html/
RUN service php7.3-fpm start
RUN chown -R www-data:www-data /var/www/html
RUN apt-get install -y curl
WORKDIR /var/www/html
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

COPY t.sh t.sh
RUN chmod +x t.sh

ENTRYPOINT [ "sh","./t.sh" ] 

CMD  ["/usr/sbin/php-fpm7.3", "--nodaemonize"]
