version: '3.3'

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./srcs/mariadb
    volumes:
      - myDb:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
  
  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    build: ./srcs/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - myVol:/var/www/html/
    restart: always
  
  nginx:
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx
    build: ./srcs/nginx
    ports:
      - 443:443
    volumes:
      - myVol:/var/www/html/
    restart: always

volumes:
  myVol:
  myDb: