FROM debian:buster

RUN apt-get update && apt-get install -y nginx openssl
RUN mkdir /etc/nginx/ssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx_key.pem -out /etc/nginx/ssl/nginx_certificate.pem -subj '/CN=localhost'
COPY nginx.conf /etc/nginx/
EXPOSE 443

CMD [ "nginx","-g","daemon off;" ]
