FROM debian:buster

RUN apt-get update -y && apt-get install -y mariadb-server

COPY init.sql /var/www/init.sql
RUN chmod 777 /var/www/init.sql
RUN sed -i '28s/bind-address/# bind-address/'  /etc/mysql/mariadb.conf.d/50-server.cnf
RUN sed -i '19s/#port/port/'  /etc/mysql/mariadb.conf.d/50-server.cnf
RUN service mysql start && mysql -u root < /var/www/init.sql

CMD ["mysqld_safe"]